### ISSUE TITLE
Conditional ML Model Training Trigger Based on New Training Data in GitHub Actions

### ISSUE THREAD

**Issue by zarfld** [zarfld/circuit_recognizer#20]
### Overview

This specification describes how to set up a **conditional trigger** for training a machine learning (ML) model in a GitHub Actions CI/CD pipeline. The training will only be triggered when a certain number of new training data files (e.g., images or CSVs) have been added to the dataset since the last training session. The count of new files is compared to a stored record, and training will only occur if the new files exceed a predefined threshold.

### Components

1. **File Count Tracking**: Store the count of training files from the last session in a file (`previous_count.txt`).
2. **Data Comparison Script**: A Python script (`check_new_data.py`) that compares the current number of training data files to the stored count in `previous_count.txt`.
3. **GitHub Actions Workflow**: Automates the conditional execution of the training process based on the result of the comparison script.
4. **Training Job**: Triggers the training process using `train_model.py` when sufficient new data files are detected.
5. **Dataset Location**: Ensure that the dataset is stored in a location accessible by the workflow (repository folder, cloud storage, etc.).

### Pre-Requisites

- **GitHub Repository**: The repository should already include your training code (`train_model.py`), dependencies (e.g., `requirements.txt`), and any other necessary scripts.
- **Training Data Storage**: The training data should be available in a specific folder in the repository or accessible via cloud storage.
- **Previous Data Count File**: The `previous_count.txt` file should be added to the repository to store the count of training data from the last session.

---

#### 1. **File Count Tracking**

A file (`previous_count.txt`) will store the count of the number of training data files processed in the last training session. This file should be located in the repository or a shared cloud location that can be accessed by the GitHub Actions workflow.

- Example contents of `previous_count.txt`:

    ```txt
    150  # This represents the number of data files counted in the last session
    ```

#### 2. **Data Comparison Script**

A Python script (`check_new_data.py`) will be used to:
- Count the current number of training data files.
- Compare this count with the number stored in `previous_count.txt`.
- Determine if the difference in counts meets the specified threshold (e.g., 10 new files).

##### `check_new_data.py`

```python
import os

# Path to the dataset directory
dataset_dir = 'dataset/'  # Update with your actual dataset directory

# Path to the file that stores the previous count
previous_count_file = 'previous_count.txt'

# Threshold for the number of new files that trigger a training session
threshold = 10

def get_current_data_count():
    """Count the number of files in the dataset directory."""
    return len([f for f in os.listdir(dataset_dir) if os.path.isfile(os.path.join(dataset_dir, f))])

def get_previous_data_count():
    """Read the previous data count from the file."""
    if os.path.exists(previous_count_file):
        with open(previous_count_file, 'r') as file:
            return int(file.read().strip())
    return 0

def update_previous_data_count(new_count):
    """Update the previous data count in the file."""
    with open(previous_count_file, 'w') as file:
        file.write(str(new_count))

if __name__ == "__main__":
    current_count = get_current_data_count()
    previous_count = get_previous_data_count()

    new_files_count = current_count - previous_count

    if new_files_count >= threshold:
        print(f"New files detected: {new_files_count}, triggering training.")
        update_previous_data_count(current_count)
        exit(0)  # Exit with status 0 to trigger training
    else:
        print(f"Only {new_files_count} new files, training not triggered.")
        exit(1)  # Exit with status 1 to skip training
```

#### 3. **GitHub Actions Workflow**

The GitHub Actions workflow will:
- Check if the number of new files exceeds the threshold.
- Trigger the training if the new data condition is met.
- Upload the trained model (optional).

Create a workflow file `.github/workflows/train_model.yml` in your repository.

##### `train_model.yml`

```yaml
name: Conditional Model Training

on:
  push:
    branches:
      - main
    paths:
      - 'dataset/**'   # Monitor changes in the dataset directory

jobs:
  check-and-train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure this includes necessary libraries like TensorFlow

    - name: Check new training data
      run: python check_new_data.py

    - name: Run training job
      if: success()  # This ensures that training only runs if the previous step (checking new data) succeeds
      run: |
        python train_model.py

    - name: Upload trained model
      if: success()  # Optional: Upload trained model if training was triggered
      run: |
        gsutil cp saved_model/my_model gs://your-bucket/models/
      env:
  
```

#### 4. **Training Job**

The script `train_model.py` should handle the actual training of the model. This script could use TensorFlow, PyTorch, or any other ML framework. After training, the model can be saved to the `saved_model/` directory or any other location.

Example `train_model.py`:

```python
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten
from tensorflow.keras.preprocessing.image import ImageDataGenerator

def load_data():
    # Load and preprocess your data
    train_data_gen = ImageDataGenerator(rescale=1./255).flow_from_directory('dataset/train/', target_size=(150, 150))
    val_data_gen = ImageDataGenerator(rescale=1./255).flow_from_directory('dataset/val/', target_size=(150, 150))
    return train_data_gen, val_data_gen

def build_model():
    model = Sequential([
        Conv2D(32, (3,3), activation='relu', input_shape=(150, 150, 3)),
        Flatten(),
        Dense(128, activation='relu'),
        Dense(10, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

def train_model():
    train_data, val_data = load_data()
    model = build_model()
    model.fit(train_data, epochs=10, validation_data=val_data)
    model.save('saved_model/my_model')

if __name__ == '__main__':
    train_model()
```

---

### Full Workflow Summary

1. **Tracking New Data**:  
   The `check_new_data.py` script is used to track how many new files have been added since the last training session. This count is compared to the previous count stored in `previous_count.txt`.

2. **GitHub Actions Workflow**:  
   The workflow listens for pushes to the main branch and specifically looks for changes in the dataset directory. The workflow first runs `check_new_data.py` to check if the new files exceed the threshold (e.g., 10 new files). If the condition is met, the training job proceeds.

3. **Conditional Trigger**:  
   Training is triggered based on the result of the file count comparison. If there aren’t enough new files, training is skipped.

4. **Model Training and Storage**:  
   If training is triggered, the `train_model.py` script runs the model training, and the trained model is optionally uploaded to cloud storage

---

### Acceptance Criteria

1. **New Data Detection**:  
   The workflow successfully detects new files in the dataset and triggers training if the specified threshold (e.g., 10 new files) is met.

2. **Conditional Training Execution**:  
   Training is only triggered when sufficient new data has been added. If fewer than the required number of files are added, training does not occur.

3. **Workflow Functionality**:  
   The GitHub Actions workflow runs successfully, installs dependencies, checks the dataset, and conditionally executes the training.

4. **Model Storage**:  
   The trained model is saved locally in the repository and optionally uploaded to cloud storage 

---

### Optional Extensions

- **Versioning the Model**: You can add logic to version the trained models by tagging them based on timestamp or Git commit hash.
- **Monitoring and Logging**: Integrate with services like TensorBoard or WandB for monitoring and logging the training process.

---

This full specification provides a complete setup for conditionally triggering an ML model training process using GitHub Actions based on the number of new files added to the dataset.
